### ISSUE TITLE
Only using one LCZoomTransition for one action

### ISSUE THREAD

**Issue by gconno** [mluisbrown/LCZoomTransition#6]
Hi,
Great library. Im having an issue though. If I add:

```
 self.zoomTransition = [[LCZoomTransition alloc] initWithNavigationController:self.navigationController];
```

It effects all my segues, is it possible to only target individual segues? For example, I only want to use it on one push segue in my app, not all in that activity.

Thanks

**Comment by mluisbrown** [comment]
Hi,

At the moment, I don't think it's possible to affect only one segue. I need to think of a clean way to enable this.

Thanks.

**Comment by mluisbrown** [comment]
Ok, the problem is that `[[LCZoomTransition alloc] initWithNavigationController:self.navigationController]` it is setting the `UINavigationController delegate` to `self`. This makes it apply to all segues for that navigation controller. As a workaround, you could set `self.navigationController.delegate = nil;` in `prepareForSegue` for segue's where you don't want the transition. If you do that you'll need to make sure you do `self.navigationController.delegate = self.zoomTransition;` in `prepareForSegue` for the segue(s) where you _do_ want the transition.
